<?php


namespace App\Tests\Shared\Domain;


use App\Shared\Domain\InvalidValueException;
use App\Shared\Domain\UuidFactory;
use App\Shared\Service\UuidValidatorInterface;
use App\Infrastructure\Service\UuidValidatorAdapter;
use PHPUnit\Framework\TestCase;
use Ramsey\Uuid\Uuid;

class UuidFactoryTest extends TestCase
{
    /**
     * @var UuidValidatorInterface|\PHPUnit\Framework\MockObject\MockObject
     */
    private $validator;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->validator = $this->createMock(UuidValidatorInterface::class);
    }

    public function testCreateFromString()
    {
        $this->validator->method('isValid')->willReturn(true);
        $factory = new UuidFactory($this->validator);
        $uuidObject = Uuid::uuid4();

        $uuid = $factory->fromString($uuidObject->toString());

        $this->assertInstanceOf(\App\Shared\Domain\Uuid::class, $uuid);
    }

    public function testFailCreateFromString()
    {
        $this->validator->method('isValid')->willReturn(false);
        $factory = new UuidFactory($this->validator);
        $wrongUuid = 'some wrong string';

        $this->expectException(InvalidValueException::class);

        $uuid = $factory->fromString($wrongUuid);

        $this->fail('Expected InvalidValueException');
    }

    public function testGenerateNew()
    {
        $this->validator->method('isValid')->willReturn(true);
        $factory = new UuidFactory($this->validator);
        $uuid = $factory->generateNew();

        $this->assertInstanceOf(\App\Shared\Domain\Uuid::class, $uuid);
    }
}