#index:
#    path: /
#    controller: App\Controller\DefaultController::index

school_index:
  path: /school
  controller: App\Learning\Infrastructure\Controller\SchoolController::index
  methods: GET